# Generated by Django 4.1.7 on 2023-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Количество")),
                (
                    "picture",
                    models.ImageField(
                        upload_to="static/Pererkestok/img/products/%Y/%m/%d",
                        verbose_name="Иллюстрация",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URl"),
                ),
            ],
        ),
    ]
