# Generated by Django 4.1.7 on 2023-02-28 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "Perekrestok",
            "0003_category_alter_product_options_alter_product_picture_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": ("Категория",),
                "verbose_name_plural": "Категории",
            },
        ),
    ]
