# Generated by Django 4.1.7 on 2023-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perekrestok", "0003_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costumer_info",
            name="email",
            field=models.CharField(max_length=319, verbose_name="Email"),
        ),
    ]
