# Generated by Django 4.1.7 on 2023-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perekrestok", "0005_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.IntegerField(null=True, verbose_name="Общая цена"),
        ),
    ]
