# Generated by Django 4.1.7 on 2023-03-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perekrestok", "0006_cart_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="amount",
            new_name="count",
        ),
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True, upload_to="products", verbose_name="Иллюстрация"
            ),
        ),
    ]
